# Generated by Django 4.2.5 on 2023-10-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Park', '0006_alter_car_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='current_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
