# Generated by Django 4.2.5 on 2023-10-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Park', '0007_alter_car_current_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Park.carmark'),
            preserve_default=False,
        ),
    ]
